### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by F3ary** [charleshacks/chCasinoWall#1]
I can't really submit much but I'm already running the build 2060 on the server and updated my server to the latest artifact and spend the past 3 hours trying to figure it out but I just couldn't get it to work. I have my casino loading and everything is fine, even my penthouse is ipl loaded within the server. I tried starting up on player tp, on resource startup, and command execute, and nothing seemed to work. I look forward for your slot machine and race track and I really love your work on this script too but I really hope I'm just missing smth lol I have read the info on it more than I can count, went thru the code myself to try and maybe change something that the fivem build missed up or smth but no good.

**Comment by FlavioMoretti** [comment]
I have the same problem, both on 2060 and 2189 I cannot get it to work. I've even tried going to the Canary build. Ivé also tried using the events or integreting it into another script. None of them worked.

**Comment by charleshacks** [comment]
Hey @F3ary and @DonTosti.

Unfortunately I'm not able to reproduce your issues at all. The only thing I could imagine is a mismatch in which IPLs we're using.

Here's my exact setup:

- I'm using OneSync Infinity and 2060. Example: `D:\FXServer\server\FXServer.exe +exec server.cfg +set onesync on +set sv_enforceGameBuild 2060`
- I'm using bob74_ipl [with this PR](https://github.com/Bob74/bob74_ipl/pull/23/files) to load the casino IPLs.
- I'm using the below commands (just slapped on the bottom of `client/client.lua` to test.)
- I teleport to `vector3(1100.0, 220.0, -50.0)`
- I run `/ontest` and the video wall starts.
- I run `/offtest` and the video wall freezes.
- I run `/ontest` and the video wall restarts.
- I run `/wintest` and the confetti plays then resets back to falling diamonds.

```lua
RegisterCommand('ontest', function()
    TriggerEvent(Config.EnterEvent)
end)

RegisterCommand('offtest', function()
    TriggerEvent(Config.ExitEvent)
end)

RegisterCommand('wintest', function()
    TriggerEvent(Config.BigWinEvent)
end)
```

**Comment by F3ary** [comment]
Hey sorry forgot to give a feedback, I got the casino working. I had everything the same and I even used the same commands u did lol, but the issue was the ipl loader I had, it was using another casino version which is the ct_"smth idk" but beside that everything is working great now thank you. Also do we have an ETA on the other casino scripts ? just checking on them bc I'm also waiting on them lol

**Comment by iFailure1** [comment]
> Hey sorry forgot to give a feedback, I got the casino working. I had everything the same and I even used the same commands u did lol, but the issue was the ipl loader I had, it was using another casino version which is the ct_"smth idk" but beside that everything is working great now thank you. Also do we have an ETA on the other casino scripts ? just checking on them bc I'm also waiting on them lol

Could you help me out by letting me know which interior IPL u are using, I am using Bob74 but can't get it to load even following charles steps.

**Comment by F3ary** [comment]
> > Hey sorry forgot to give a feedback, I got the casino working. I had everything the same and I even used the same commands u did lol, but the issue was the ipl loader I had, it was using another casino version which is the ct_"smth idk" but beside that everything is working great now thank you. Also do we have an ETA on the other casino scripts ? just checking on them bc I'm also waiting on them lol
> 
> 
> 
> Could you help me out by letting me know which interior IPL u are using, I am using Bob74 but can't get it to load even following charles steps.

I used this Ipl loader called srp-ipl:

https://github.com/VSSVSSN/srp-ipl-v2

Just set the casino to true and run the script then go to the coords of the casino mentioned earlier and should work.

**Comment by iFailure1** [comment]
> > > Hey sorry forgot to give a feedback, I got the casino working. I had everything the same and I even used the same commands u did lol, but the issue was the ipl loader I had, it was using another casino version which is the ct_"smth idk" but beside that everything is working great now thank you. Also do we have an ETA on the other casino scripts ? just checking on them bc I'm also waiting on them lol
> > 
> > 
> > Could you help me out by letting me know which interior IPL u are using, I am using Bob74 but can't get it to load even following charles steps.
> 
> I used this Ipl loader called srp-ipl:
> 
> https://github.com/VSSVSSN/srp-ipl-v2
> 
> Just set the casino to true and run the script then go to the coords of the casino mentioned earlier and should work.

Thanks so much!! Gonna try it rn I will let u know how it goes :)

**Comment by iFailure1** [comment]
> > > Hey sorry forgot to give a feedback, I got the casino working. I had everything the same and I even used the same commands u did lol, but the issue was the ipl loader I had, it was using another casino version which is the ct_"smth idk" but beside that everything is working great now thank you. Also do we have an ETA on the other casino scripts ? just checking on them bc I'm also waiting on them lol
> > 
> > 
> > Could you help me out by letting me know which interior IPL u are using, I am using Bob74 but can't get it to load even following charles steps.
> 
> I used this Ipl loader called srp-ipl:
> 
> https://github.com/VSSVSSN/srp-ipl-v2
> 
> Just set the casino to true and run the script then go to the coords of the casino mentioned earlier and should work.

It's so odd, haha. Still teleports me into the oblivion. I thought I was decent at map mods but this one has me stumped. I installed srp-ipl, made sure to check config and it is in fact true. i disabled bob74ipl, still no luck. So odd... there has to be something somewhere disabling it. Resource does startup with no errors however.

**Comment by iFailure1** [comment]
Im dumb lol, I did all this and forgot to modify my exec orders, all is working fine now

**Comment by minipunch** [comment]
+1 on this

I tried with both the IPL the OP said you were using as well as ``srp-ipl``, no luck with either

I give up lol
