### ISSUE TITLE
Screen paused.

### ISSUE THREAD

**Issue by neiltary** [charleshacks/chCasinoWall#2]
Hello, I have configured your script with the teleport, when it enters it lights up the walls perfectly, and when you leave it pauses too ... but if you re-enter the screens they do not go back into animation.
------------------------------------------------------

in an improvement to your script, could you please put the screen "ch_chint01_betting_sreens" for the inner track?
for this script: https://forum.cfx.re/t/standalone-inside-track-horse-bet/2293659/33

**Comment by julhenri** [comment]
same issue here!

**Comment by charleshacks** [comment]
Make sure you are triggering the enter event when you re-enter. I'm unable to reproduce this issue. Below is what I am using for testing.

```lua
RegisterCommand('ontest', function()
    TriggerEvent(Config.EnterEvent)
end)

RegisterCommand('offtest', function()
    TriggerEvent(Config.ExitEvent)
end)

RegisterCommand('wintest', function()
    TriggerEvent(Config.BigWinEvent)
end)
```

1. I run `/ontest` and the screens begin.
2. I run `/offtest` and the screens freeze.
3. I run `/ontest` and the screens begin again.
4. I run `/wintest` and the confetti plays, then goes back to falling diamonds.
5. I run `/offtest` and the screens freeze.
6. I run `/ontest` and the screens begin again.

**Comment by Senlar** [comment]
I have a fix for this.
